name: Continuous Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.13

      - name: Add git credentials
        env:
          TOKEN: ${{ secrets.RUNNER_DEP_HANDLER }}
        run: git config --global url.https://$TOKEN@github.com.insteadOf https://github.com

      - name: Update Dependencies
        env:
          GOPRIVATE: github.com/breno-ca/private-repo
        run: |
          go env -w GOPRIVATE=$GOPRIVATE && \
          go get -u

      - name: Run Main
        env:
          TOKEN: ${{ secrets.TEST_TOKEN }}
        run: TEST_TOKEN=$TOKEN go run main.go
