name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Dependencies
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRIVATE_REPO_URL: github.com/breno-ca/private-repo
          GIT_THIS: url.https://user:$TOKEN@github.com/
        run: |
          git config --global $GIT_THIS.instead https://github.com; \
          go env -w GOPRIVATE=$PRIVATE_REPO_URL && \
          go get -u

      - name: Run Main
        run: go run main.go
    
