name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Dependencies
        run: go get -u

      - name: Run Main
        run: go run main.go
    
