name: Continuous Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.13

      - name: Add git credentials
        env:
          TOKEN: ${{ secrets.RUNNER_DEP_HANDLER }}
        run: git config --global url.https://$TOKEN@github.com.insteadOf https://github.com

      - name: Update Dependencies
        env:
          GOPRIVATE: github.com/breno-ca/private-repo
        run: |
          go env -w GOPRIVATE=$GOPRIVATE && \
          go mod tidy

      - name: Prepare to cache docker images
        run: mkdir -p ~/image-cache
      
      - name: Setup caching
        id : image-cache
        uses: actions/cache@v4
        with:
          path: ~/image-cache
          key: image-cache-${{ runner.os }}
      
      - name: Pull again if cache miss
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          docker pull mysql:8.0.36; \
          docker save -o ~/image-cache/mysql-8.0.36.tar mysql:8.0.36
          docker pull redis:7; \
          docker save -o ~/image-cache/redis-7.tar redis:7

      - name: Get cache if hit
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i ~/image-cache/mysql-8.0.36.tar; \
          docker load -i ~/image-cache/redis-7.tar

      - name: Run Main
        env:
          TOKEN: ${{ secrets.TEST_TOKEN }}
        run: TEST_TOKEN=$TOKEN go run main.go
