name: Testing optional inputs
on:
  workflow_call:
    inputs:
      mandatory:
        type: string
        required: true
      optional:
        type: boolean
        required: false
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MANDATORY: ${{ inputs.mandatory }}
      OPTIONAL: ${{ inputs.optional }}
    steps:
      - name: Echo mandatory
        run: echo $MANDATORY

      - name: Install pngquant and mozjpeg
        if: ${{ inputs.optional == true }}
        run: |
          echo $OPTIONAL; \
          sudo apt install pngquant -y; \
          cd /opt/; \
          sudo git clone https://github.com/mozilla/mozjpeg.git; \
          cd mozjpeg/ ; \
          sudo cmake -G"Unix Makefiles" .; \
          sudo make; \
          sudo make install; \
